In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("nba.csv")
print(df)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN

[458 rows x 9 columns]

In [4]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='str')

In [5]:
df["Team"]

0      Boston Celtics
1      Boston Celtics
2      Boston Celtics
3      Boston Celtics
4      Boston Celtics
            ...
453         Utah Jazz
454         Utah Jazz
455         Utah Jazz
456         Utah Jazz
457               NaN
Name: Team, Length: 458, dtype: str

In [7]:
df1=df[["Name","Salary"]]
df1

              Name     Salary
0    Avery Bradley  7730337.0
1      Jae Crowder  6796117.0
2     John Holland        NaN
3      R.J. Hunter  1148640.0
4    Jonas Jerebko  5000000.0
..             ...        ...
453   Shelvin Mack  2433333.0
454      Raul Neto   900000.0
455   Tibor Pleiss  2900000.0
456    Jeff Withey   947276.0
457            NaN        NaN

[458 rows x 2 columns]

In [11]:
df["Experience"] = 2

In [12]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2

In [15]:
df["Salary_after_bonus"] = df["Salary"] * 1.10
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0

In [16]:
df2=df.drop("Experience", axis=1)
df2

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,5500000.0
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2676666.3
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,990000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,3190000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,1042003.6
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df3=df2.drop("Salary_after_bonus", axis=1)
df3

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
new_row = {
    "Name": "Emma",
    "Team":"Boston Celtics",
    "Number":99.0,
    "Position": "SG",
    "Age":25,
    "Height":"6-10",
    "Weight":231.0,
    "College":"Butler",
    
    "Salary":900000
}

new_df = pd.DataFrame([new_row])

print(new_df)
print("*"*90)
print()

df4 = pd.concat([df3, new_df], ignore_index=True)
print(df4)

   Name            Team  Number Position  Age Height  Weight College  Salary
0  Emma  Boston Celtics    99.0       SG   25   6-10   231.0  Butler  900000
******************************************************************************************

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN
458             Butler   900000.0

[459 rows x 9 columns]

In [20]:
df4.drop(457, inplace=True)
print(df4)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
458             Butler   900000.0

[458 rows x 9 columns]

In [21]:
df4.drop(1, inplace=True)
print(df4)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

               College      Salary
0                Texas   7730337.0
2    Boston University         NaN
3        Georgia State   1148640.0
4                  NaN   5000000.0
5                  NaN  12000000.0
..                 ...         ...
453             Butler   2433333.0
454                NaN    900000.0
455                NaN   2900000.0
456             Kansas    947276.0
458             Butler    900000.0

[457 rows x 9 columns]

In [22]:
df4.reset_index(drop=True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
2,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
3,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
4,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
...,...,...,...,...,...,...,...,...,...
452,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
453,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
454,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
455,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
456,Emma,Boston Celtics,99.0,SG,25.0,6-10,231.0,Butler,900000.0

### Loc and Iloc

In [27]:
data = {
    "Name" : ["Alice","Bob","Charlie","David","Emma"],
    "Age" : [22,56,23,45,28],
    "Dapartment" : ["HR","IT","Finance","IT","Marketing"],
    "Salary" : [40000,500000,200000,4500000,1000000]
}
df = pd.DataFrame(data)
df

      Name  Age Dapartment   Salary
0    Alice   22         HR    40000
1      Bob   56         IT   500000
2  Charlie   23    Finance   200000
3    David   45         IT  4500000
4     Emma   28  Marketing  1000000

In [25]:
df.loc[[2]]

      Name  Age Dapartment  Salary
2  Charlie   23    Finance  200000

In [26]:
df.loc[[1,3]]

    Name  Age Dapartment   Salary
1    Bob   56         IT   500000
3  David   45         IT  4500000

In [28]:
df.loc[2,"Name"]

'Charlie'

In [29]:
df.loc[2,["Name","Salary"]]

Name      Charlie
Salary     200000
Name: 2, dtype: object

In [31]:
df.loc[[1,3],["Name","Dapartment"]]

    Name Dapartment
1    Bob         IT
3  David         IT

In [32]:
df.loc[1:3]

      Name  Age Dapartment   Salary
1      Bob   56         IT   500000
2  Charlie   23    Finance   200000
3    David   45         IT  4500000

In [34]:
df.loc[df["Salary"] > 500000]

    Name  Age Dapartment   Salary
3  David   45         IT  4500000
4   Emma   28  Marketing  1000000

In [35]:
df.loc[df["Salary"] > 500000, ["Name","Salary"]]

    Name   Salary
3  David  4500000
4   Emma  1000000

In [39]:
df.loc[2,"Salary"] = 1234567
df

      Name  Age Dapartment   Salary
0    Alice   22         HR    40000
1      Bob   56         IT   500000
2  Charlie   23    Finance  1234567
3    David   45         IT  4500000
4     Emma   28  Marketing  1000000

In [57]:
data = {
    "Name" : ["Alice","Bob","Charlie","David","Emma"],
    "Age" : [23,28,30,26,39],
    "Department" : ["HR","IT","Finance","IT","Marketing"],
    "Salary":[400000,500000,7500000,550000,6900000]
}
df = pd.DataFrame(data,index = [x for x in "abcde"])
# df = pd.DataFrame(data,index=["A","B","C","D","E"])
print(df)

      Name  Age Department   Salary
a    Alice   23         HR   400000
b      Bob   28         IT   500000
c  Charlie   30    Finance  7500000
d    David   26         IT   550000
e     Emma   39  Marketing  6900000

In [59]:
df.loc["a"]

Name           Alice
Age               23
Department        HR
Salary        400000
Name: a, dtype: object

In [53]:
df.iloc[1]

Name             Bob
Age               28
Department        IT
Salary        500000
Name: B, dtype: object

In [54]:
df.loc["A":"D"]

      Name  Age Department   Salary
A    Alice   23         HR   400000
B      Bob   28         IT   500000
C  Charlie   30    Finance  7500000
D    David   26         IT   550000

In [61]:
df.iloc[0:4]

      Name  Age Department   Salary
a    Alice   23         HR   400000
b      Bob   28         IT   500000
c  Charlie   30    Finance  7500000
d    David   26         IT   550000

In [64]:
df.iloc[2]

Name          Charlie
Age                30
Department    Finance
Salary        7500000
Name: c, dtype: object

In [65]:
df.iloc[[1,3]]

    Name  Age Department  Salary
b    Bob   28         IT  500000
d  David   26         IT  550000

In [66]:
df.iloc[1,1]

np.int64(28)

In [67]:
df.iloc[1,[1,3]]

Age           28
Salary    500000
Name: b, dtype: int64

In [68]:
df.iloc[:,1:3]

   Age Department
a   23         HR
b   28         IT
c   30    Finance
d   26         IT
e   39  Marketing

In [71]:
df.iloc[:,1]

a    23
b    28
c    30
d    26
e    39
Name: Age, dtype: int64