In [1]:
import pandas as pd

In [2]:
data = {
"Name": [
"Aarav", "Diya", "Rahul", "Ananya", "Arjun",
"Meera", "Vivek", "Sneha", "Rohan", "Priya",
"Aditya", "Kavya", "Kiran", "Neha", "Varun",
"Isha", "Nikhil", "Pooja", "Akash", "Riya",
"Manu", "Asha", "Sanjay", "Anu", "Vishnu",
"Maya", "Rakesh", "Lakshmi", "Abhinav", "Nandini",
"Surya", "Deepa", "Hari", "Swathi", "Ajay",
"Reshma", "Suresh", "Amritha", "Joel", "Fathima",
"Kevin", "Athira", "Alan", "Gopika", "Shyam",
"Sandra", "Thomas", "Anjali", "Joseph", "Mariya"
],
"Age": [
21, 22, 23, 21, 24,
22, 25, 23, 21, 24,
26, 22, 23, 25, 21,
24, 22, 26, 23, 21,
25, 24, 22, 23, 26,
21, 25, 24, 22, 23,
26, 21, 24, 25, 22,
23, 26, 21, 24, 22,
25, 23, 21, 26, 24,
22, 25, 23, 21, 26
],
"Department": [
"IT", "HR", "Finance", "IT", "Marketing",
"IT", "Finance", "HR", "IT", "Sales",
"Finance", "IT", "HR", "Marketing", "Sales",
"IT", "Finance", "HR", "IT", "Marketing",
"Sales", "IT", "Finance", "HR", "IT",
"Marketing", "Sales", "Finance", "IT", "HR",
"IT", "Sales", "Finance", "Marketing", "IT",
"HR", "Finance", "IT", "Sales", "Marketing",
"IT", "HR", "Finance", "IT", "Marketing",
"Sales", "Finance", "HR", "IT", "Sales"
],
"Salary": [
35000, 32000, 40000, 38000, 45000,
42000, 50000, 34000, 37000, 41000,
52000, 39000, 36000, 48000, 43000,
46000, 44000, 35000, 40000, 47000,
38000, 51000, 42000, 36000, 45000,
39000, 53000, 41000, 46000, 37000,
49000, 43000, 40000, 52000, 38000,
35000, 54000, 44000, 39000, 47000,
50000, 36000, 45000, 41000, 53000,
38000, 46000, 42000, 35000, 49000
],
"Score": [
85, 78, 92, 88, 95,
81, 90, 76, 84, 89,
93, 87, 79, 91, 86,
94, 82, 88, 90, 77,
83, 96, 85, 80, 92,
74, 89, 91, 86, 78,
95, 82, 88, 93, 80,
76, 90, 84, 87, 92,
89, 79, 94, 85, 91,
83, 88, 86, 75, 90
]
}

df = pd.DataFrame(data)

# Loc Solution

In [3]:
df.loc[5]

Name          Meera
Age              22
Department       IT
Salary        42000
Score            81
Name: 5, dtype: object

In [5]:
df.loc[10:20]

      Name  Age Department  Salary  Score
10  Aditya   26    Finance   52000     93
11   Kavya   22         IT   39000     87
12   Kiran   23         HR   36000     79
13    Neha   25  Marketing   48000     91
14   Varun   21      Sales   43000     86
15    Isha   24         IT   46000     94
16  Nikhil   22    Finance   44000     82
17   Pooja   26         HR   35000     88
18   Akash   23         IT   40000     90
19    Riya   21  Marketing   47000     77
20    Manu   25      Sales   38000     83

In [6]:
df.loc[:,"Name"]

0       Aarav
1        Diya
2       Rahul
3      Ananya
4       Arjun
5       Meera
6       Vivek
7       Sneha
8       Rohan
9       Priya
10     Aditya
11      Kavya
12      Kiran
13       Neha
14      Varun
15       Isha
16     Nikhil
17      Pooja
18      Akash
19       Riya
20       Manu
21       Asha
22     Sanjay
23        Anu
24     Vishnu
25       Maya
26     Rakesh
27    Lakshmi
28    Abhinav
29    Nandini
30      Surya
31      Deepa
32       Hari
33     Swathi
34       Ajay
35     Reshma
36     Suresh
37    Amritha
38       Joel
39    Fathima
40      Kevin
41     Athira
42       Alan
43     Gopika
44      Shyam
45     Sandra
46     Thomas
47     Anjali
48     Joseph
49     Mariya
Name: Name, dtype: str

In [7]:
df.loc[:,["Name","Salary"]]

       Name  Salary
0     Aarav   35000
1      Diya   32000
2     Rahul   40000
3    Ananya   38000
4     Arjun   45000
5     Meera   42000
6     Vivek   50000
7     Sneha   34000
8     Rohan   37000
9     Priya   41000
10   Aditya   52000
11    Kavya   39000
12    Kiran   36000
13     Neha   48000
14    Varun   43000
15     Isha   46000
16   Nikhil   44000
17    Pooja   35000
18    Akash   40000
19     Riya   47000
20     Manu   38000
21     Asha   51000
22   Sanjay   42000
23      Anu   36000
24   Vishnu   45000
25     Maya   39000
26   Rakesh   53000
27  Lakshmi   41000
28  Abhinav   46000
29  Nandini   37000
30    Surya   49000
31    Deepa   43000
32     Hari   40000
33   Swathi   52000
34     Ajay   38000
35   Reshma   35000
36   Suresh   54000
37  Amritha   44000
38     Joel   39000
39  Fathima   47000
40    Kevin   50000
41   Athira   36000
42     Alan   45000
43   Gopika   41000
44    Shyam   53000
45   Sandra   38000
46   Thomas   46000
47   Anjali   42000
48   Joseph   35000
49   Mariya   49000

In [9]:
df.loc[5:15,'Name':'Salary']

      Name  Age Department  Salary
5    Meera   22         IT   42000
6    Vivek   25    Finance   50000
7    Sneha   23         HR   34000
8    Rohan   21         IT   37000
9    Priya   24      Sales   41000
10  Aditya   26    Finance   52000
11   Kavya   22         IT   39000
12   Kiran   23         HR   36000
13    Neha   25  Marketing   48000
14   Varun   21      Sales   43000
15    Isha   24         IT   46000

In [10]:
df.loc[df['Department'] == 'IT']

       Name  Age Department  Salary  Score
0     Aarav   21         IT   35000     85
3    Ananya   21         IT   38000     88
5     Meera   22         IT   42000     81
8     Rohan   21         IT   37000     84
11    Kavya   22         IT   39000     87
15     Isha   24         IT   46000     94
18    Akash   23         IT   40000     90
21     Asha   24         IT   51000     96
24   Vishnu   26         IT   45000     92
28  Abhinav   22         IT   46000     86
30    Surya   26         IT   49000     95
34     Ajay   22         IT   38000     80
37  Amritha   21         IT   44000     84
40    Kevin   25         IT   50000     89
43   Gopika   26         IT   41000     85
48   Joseph   21         IT   35000     75

In [12]:
df.loc[df["Salary"] > 45000]

       Name  Age Department  Salary  Score
6     Vivek   25    Finance   50000     90
10   Aditya   26    Finance   52000     93
13     Neha   25  Marketing   48000     91
15     Isha   24         IT   46000     94
19     Riya   21  Marketing   47000     77
21     Asha   24         IT   51000     96
26   Rakesh   25      Sales   53000     89
28  Abhinav   22         IT   46000     86
30    Surya   26         IT   49000     95
33   Swathi   25  Marketing   52000     93
36   Suresh   26    Finance   54000     90
39  Fathima   22  Marketing   47000     92
40    Kevin   25         IT   50000     89
44    Shyam   24  Marketing   53000     91
46   Thomas   25    Finance   46000     88
49   Mariya   26      Sales   49000     90

In [14]:
df.loc[df["Department"] == "Finance" , ['Name','Salary']]

       Name  Salary
2     Rahul   40000
6     Vivek   50000
10   Aditya   52000
16   Nikhil   44000
22   Sanjay   42000
27  Lakshmi   41000
32     Hari   40000
36   Suresh   54000
42     Alan   45000
46   Thomas   46000

In [15]:
df.loc[[2,7,12,20,30]]

     Name  Age Department  Salary  Score
2   Rahul   23    Finance   40000     92
7   Sneha   23         HR   34000     76
12  Kiran   23         HR   36000     79
20   Manu   25      Sales   38000     83
30  Surya   26         IT   49000     95

In [18]:
df.loc[5,"Salary"] = 60000
df.loc[[5]]

    Name  Age Department  Salary  Score
5  Meera   22         IT   60000     81

In [21]:
df.loc[df['Department'] == 'IT' , 'Score'] = 100
df.loc[df['Department'] == 'IT']

       Name  Age Department  Salary  Score
0     Aarav   21         IT   35000    100
3    Ananya   21         IT   38000    100
5     Meera   22         IT   60000    100
8     Rohan   21         IT   37000    100
11    Kavya   22         IT   39000    100
15     Isha   24         IT   46000    100
18    Akash   23         IT   40000    100
21     Asha   24         IT   51000    100
24   Vishnu   26         IT   45000    100
28  Abhinav   22         IT   46000    100
30    Surya   26         IT   49000    100
34     Ajay   22         IT   38000    100
37  Amritha   21         IT   44000    100
40    Kevin   25         IT   50000    100
43   Gopika   26         IT   41000    100
48   Joseph   21         IT   35000    100

In [22]:
df.loc[df['Age'] > 23, ['Name', 'Age', 'Department']]

       Name  Age Department
4     Arjun   24  Marketing
6     Vivek   25    Finance
9     Priya   24      Sales
10   Aditya   26    Finance
13     Neha   25  Marketing
15     Isha   24         IT
17    Pooja   26         HR
20     Manu   25      Sales
21     Asha   24         IT
24   Vishnu   26         IT
26   Rakesh   25      Sales
27  Lakshmi   24    Finance
30    Surya   26         IT
32     Hari   24    Finance
33   Swathi   25  Marketing
36   Suresh   26    Finance
38     Joel   24      Sales
40    Kevin   25         IT
43   Gopika   26         IT
44    Shyam   24  Marketing
46   Thomas   25    Finance
49   Mariya   26      Sales

In [25]:
df.loc[df['Department'].isin(['HR' ,'Finance'])]

       Name  Age Department  Salary  Score
1      Diya   22         HR   32000     78
2     Rahul   23    Finance   40000     92
6     Vivek   25    Finance   50000     90
7     Sneha   23         HR   34000     76
10   Aditya   26    Finance   52000     93
12    Kiran   23         HR   36000     79
16   Nikhil   22    Finance   44000     82
17    Pooja   26         HR   35000     88
22   Sanjay   22    Finance   42000     85
23      Anu   23         HR   36000     80
27  Lakshmi   24    Finance   41000     91
29  Nandini   23         HR   37000     78
32     Hari   24    Finance   40000     88
35   Reshma   23         HR   35000     76
36   Suresh   26    Finance   54000     90
41   Athira   23         HR   36000     79
42     Alan   21    Finance   45000     94
46   Thomas   25    Finance   46000     88
47   Anjali   23         HR   42000     86

In [27]:
df.loc[(df['Salary'] >= 45000) & (df['Score'] >= 90)]

       Name  Age Department  Salary  Score
4     Arjun   24  Marketing   45000     95
5     Meera   22         IT   60000    100
6     Vivek   25    Finance   50000     90
10   Aditya   26    Finance   52000     93
13     Neha   25  Marketing   48000     91
15     Isha   24         IT   46000    100
21     Asha   24         IT   51000    100
24   Vishnu   26         IT   45000    100
28  Abhinav   22         IT   46000    100
30    Surya   26         IT   49000    100
33   Swathi   25  Marketing   52000     93
36   Suresh   26    Finance   54000     90
39  Fathima   22  Marketing   47000     92
40    Kevin   25         IT   50000    100
42     Alan   21    Finance   45000     94
44    Shyam   24  Marketing   53000     91
49   Mariya   26      Sales   49000     90

# Iloc Solution

In [29]:
df.iloc[[0]]

    Name  Age Department  Salary  Score
0  Aarav   21         IT   35000    100

In [30]:
df.iloc[9]

Name          Priya
Age              24
Department    Sales
Salary        41000
Score            89
Name: 9, dtype: object

In [31]:
df.iloc[0:10]

     Name  Age Department  Salary  Score
0   Aarav   21         IT   35000    100
1    Diya   22         HR   32000     78
2   Rahul   23    Finance   40000     92
3  Ananya   21         IT   38000    100
4   Arjun   24  Marketing   45000     95
5   Meera   22         IT   60000    100
6   Vivek   25    Finance   50000     90
7   Sneha   23         HR   34000     76
8   Rohan   21         IT   37000    100
9   Priya   24      Sales   41000     89

In [32]:
df.iloc[:, 0]

0       Aarav
1        Diya
2       Rahul
3      Ananya
4       Arjun
5       Meera
6       Vivek
7       Sneha
8       Rohan
9       Priya
10     Aditya
11      Kavya
12      Kiran
13       Neha
14      Varun
15       Isha
16     Nikhil
17      Pooja
18      Akash
19       Riya
20       Manu
21       Asha
22     Sanjay
23        Anu
24     Vishnu
25       Maya
26     Rakesh
27    Lakshmi
28    Abhinav
29    Nandini
30      Surya
31      Deepa
32       Hari
33     Swathi
34       Ajay
35     Reshma
36     Suresh
37    Amritha
38       Joel
39    Fathima
40      Kevin
41     Athira
42       Alan
43     Gopika
44      Shyam
45     Sandra
46     Thomas
47     Anjali
48     Joseph
49     Mariya
Name: Name, dtype: str

In [33]:
df.iloc[:, 0]

0       Aarav
1        Diya
2       Rahul
3      Ananya
4       Arjun
5       Meera
6       Vivek
7       Sneha
8       Rohan
9       Priya
10     Aditya
11      Kavya
12      Kiran
13       Neha
14      Varun
15       Isha
16     Nikhil
17      Pooja
18      Akash
19       Riya
20       Manu
21       Asha
22     Sanjay
23        Anu
24     Vishnu
25       Maya
26     Rakesh
27    Lakshmi
28    Abhinav
29    Nandini
30      Surya
31      Deepa
32       Hari
33     Swathi
34       Ajay
35     Reshma
36     Suresh
37    Amritha
38       Joel
39    Fathima
40      Kevin
41     Athira
42       Alan
43     Gopika
44      Shyam
45     Sandra
46     Thomas
47     Anjali
48     Joseph
49     Mariya
Name: Name, dtype: str

In [34]:
df.iloc[:, [0, 1]]

       Name  Age
0     Aarav   21
1      Diya   22
2     Rahul   23
3    Ananya   21
4     Arjun   24
5     Meera   22
6     Vivek   25
7     Sneha   23
8     Rohan   21
9     Priya   24
10   Aditya   26
11    Kavya   22
12    Kiran   23
13     Neha   25
14    Varun   21
15     Isha   24
16   Nikhil   22
17    Pooja   26
18    Akash   23
19     Riya   21
20     Manu   25
21     Asha   24
22   Sanjay   22
23      Anu   23
24   Vishnu   26
25     Maya   21
26   Rakesh   25
27  Lakshmi   24
28  Abhinav   22
29  Nandini   23
30    Surya   26
31    Deepa   21
32     Hari   24
33   Swathi   25
34     Ajay   22
35   Reshma   23
36   Suresh   26
37  Amritha   21
38     Joel   24
39  Fathima   22
40    Kevin   25
41   Athira   23
42     Alan   21
43   Gopika   26
44    Shyam   24
45   Sandra   22
46   Thomas   25
47   Anjali   23
48   Joseph   21
49   Mariya   26

In [35]:
df.iloc[0:5, 0:3]

     Name  Age Department
0   Aarav   21         IT
1    Diya   22         HR
2   Rahul   23    Finance
3  Ananya   21         IT
4   Arjun   24  Marketing

In [36]:
df.iloc[10:21, 1:4]

    Age Department  Salary
10   26    Finance   52000
11   22         IT   39000
12   23         HR   36000
13   25  Marketing   48000
14   21      Sales   43000
15   24         IT   46000
16   22    Finance   44000
17   26         HR   35000
18   23         IT   40000
19   21  Marketing   47000
20   25      Sales   38000

In [37]:
df.iloc[::2]

       Name  Age Department  Salary  Score
0     Aarav   21         IT   35000    100
2     Rahul   23    Finance   40000     92
4     Arjun   24  Marketing   45000     95
6     Vivek   25    Finance   50000     90
8     Rohan   21         IT   37000    100
10   Aditya   26    Finance   52000     93
12    Kiran   23         HR   36000     79
14    Varun   21      Sales   43000     86
16   Nikhil   22    Finance   44000     82
18    Akash   23         IT   40000    100
20     Manu   25      Sales   38000     83
22   Sanjay   22    Finance   42000     85
24   Vishnu   26         IT   45000    100
26   Rakesh   25      Sales   53000     89
28  Abhinav   22         IT   46000    100
30    Surya   26         IT   49000    100
32     Hari   24    Finance   40000     88
34     Ajay   22         IT   38000    100
36   Suresh   26    Finance   54000     90
38     Joel   24      Sales   39000     87
40    Kevin   25         IT   50000    100
42     Alan   21    Finance   45000     94
44    Shyam   24  Marketing   53000     91
46   Thomas   25    Finance   46000     88
48   Joseph   21         IT   35000    100

In [38]:
df.iloc[-5:]

      Name  Age Department  Salary  Score
45  Sandra   22      Sales   38000     83
46  Thomas   25    Finance   46000     88
47  Anjali   23         HR   42000     86
48  Joseph   21         IT   35000    100
49  Mariya   26      Sales   49000     90

In [39]:
df.iloc[:, -3:]

   Department  Salary  Score
0          IT   35000    100
1          HR   32000     78
2     Finance   40000     92
3          IT   38000    100
4   Marketing   45000     95
5          IT   60000    100
6     Finance   50000     90
7          HR   34000     76
8          IT   37000    100
9       Sales   41000     89
10    Finance   52000     93
11         IT   39000    100
12         HR   36000     79
13  Marketing   48000     91
14      Sales   43000     86
15         IT   46000    100
16    Finance   44000     82
17         HR   35000     88
18         IT   40000    100
19  Marketing   47000     77
20      Sales   38000     83
21         IT   51000    100
22    Finance   42000     85
23         HR   36000     80
24         IT   45000    100
25  Marketing   39000     74
26      Sales   53000     89
27    Finance   41000     91
28         IT   46000    100
29         HR   37000     78
30         IT   49000    100
31      Sales   43000     82
32    Finance   40000     88
33  Marketing   52000     93
34         IT   38000    100
35         HR   35000     76
36    Finance   54000     90
37         IT   44000    100
38      Sales   39000     87
39  Marketing   47000     92
40         IT   50000    100
41         HR   36000     79
42    Finance   45000     94
43         IT   41000    100
44  Marketing   53000     91
45      Sales   38000     83
46    Finance   46000     88
47         HR   42000     86
48         IT   35000    100
49      Sales   49000     90

In [40]:
df.iloc[[2, 5, 10, 15, 25]]

      Name  Age Department  Salary  Score
2    Rahul   23    Finance   40000     92
5    Meera   22         IT   60000    100
10  Aditya   26    Finance   52000     93
15    Isha   24         IT   46000    100
25    Maya   21  Marketing   39000     74

In [41]:
df.iloc[[5, 10, 15, 20], [0, 3]]

      Name  Salary
5    Meera   60000
10  Aditya   52000
15    Isha   46000
20    Manu   38000

In [43]:
df.iloc[[5, 3]]

     Name  Age Department  Salary  Score
5   Meera   22         IT   60000    100
3  Ananya   21         IT   38000    100

In [44]:
df.iloc[20:31, 1:5]

    Age Department  Salary  Score
20   25      Sales   38000     83
21   24         IT   51000    100
22   22    Finance   42000     85
23   23         HR   36000     80
24   26         IT   45000    100
25   21  Marketing   39000     74
26   25      Sales   53000     89
27   24    Finance   41000     91
28   22         IT   46000    100
29   23         HR   37000     78
30   26         IT   49000    100