In [1]:
import numpy as np

In [2]:
import pandas as pd

In [6]:
df = pd.read_csv("superstore.csv", encoding="cp1252")

## PART 1: DATA EXPLORATION (PANDAS)

### 1. Display the first 5 rows and last 5 rows of the dataset.

In [7]:
print("--- First 5 Rows ---")
print(df.head())
print("\n--- Last 5 Rows ---")
print(df.tail())

--- First 5 Rows ---
   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

--- Last 5 Rows ---
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
9989    9990  CA-2014-110422  1/21/2014  1/23/2014    Second Class
9990    9991  CA-2017-121258  2/26/2017   3/3/2017  Standard Class
9991    9992  CA-2017-121258  2/26/2017   3/3/2017  Standard Class
9992    9993  CA-2017-121258  2/26/2017   3/3/2017  Standard Class
9993    9994  CA-2017-119914   5/4/2017   5/9/2017    Second Class

     Customer ID     Customer Name   Segment        Country         City  ...  \
9989    TB-21400  Tom Boeckenhauer  Consumer  United States        Miami  ...
9990    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...
9991    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...
9992    DB-13060       Dave Brooks  Consumer  United States   Costa Mesa  ...
9993    CC-12220      Chris Cortes  Consumer  United States  Westminster  ...

     Postal Code  Region       Product ID         Category Sub-Category  \
9989       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991       92627    West  TEC-PH-10003645       Technology       Phones
9992       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name    Sales  Quantity  \
9989                             Ultra Door Pull Handle   25.248         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.960         2
9991                              Aastra 57i VoIP phone  258.576         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160         2

      Discount   Profit
9989       0.2   4.1028
9990       0.0  15.6332
9991       0.2  19.3932
9992       0.0  13.3200
9993       0.0  72.9480

[5 rows x 21 columns]

### 2. Display the number of rows and columns.

In [8]:
print(df.shape)

(9994, 21)

### 3. Check data types of all columns.

In [9]:
print(df.dtypes)

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

### 4. Display summary statistics for numerical columns.

In [10]:
print(df.describe())

            Row ID   Postal Code         Sales     Quantity     Discount  \
count  9994.000000   9994.000000   9994.000000  9994.000000  9994.000000
mean   4997.500000  55190.379428    229.858001     3.789574     0.156203
std    2885.163629  32063.693350    623.245101     2.225110     0.206452
min       1.000000   1040.000000      0.444000     1.000000     0.000000
25%    2499.250000  23223.000000     17.280000     2.000000     0.000000
50%    4997.500000  56430.500000     54.490000     3.000000     0.200000
75%    7495.750000  90008.000000    209.940000     5.000000     0.200000
max    9994.000000  99301.000000  22638.480000    14.000000     0.800000

            Profit
count  9994.000000
mean     28.656896
std     234.260108
min   -6599.978000
25%       1.728750
50%       8.666500
75%      29.364000
max    8399.976000

### 5. Count the missing values in each column.

In [11]:
print(df.isnull().sum())

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

### 6. Identify duplicate rows and remove them.

In [12]:
duplicate_count = df.duplicated().sum()
print(f"\nDuplicate rows found: {duplicate_count}")
df = df.drop_duplicates()

Duplicate rows found: 0

### 7. List all unique categories in Category and Sub-Category.

In [13]:
print("\n--- Unique Categories ---")
print(df["Category"].unique())
print("\n--- Unique Sub-Categories ---")
print(df["Sub-Category"].unique())

--- Unique Categories ---
<ArrowStringArray>
['Furniture', 'Office Supplies', 'Technology']
Length: 3, dtype: str

--- Unique Sub-Categories ---
<ArrowStringArray>
[  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
 'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
       'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

### 8. Find the top 10 most expensive products (Unit Price).

In [14]:
if "Unit Price" not in df.columns:
    df["Unit Price"] = df["Sales"] / df["Quantity"]

top_10_expensive = df[["Product Name", "Unit Price"]].drop_duplicates().nlargest(10, "Unit Price")
print("\n--- Top 10 Most Expensive Products ---")
print(top_10_expensive)

--- Top 10 Most Expensive Products ---
                                           Product Name  Unit Price
2697  Cisco TelePresence System EX90 Videoconferenci...    3773.080
6826              Canon imageCLASS 2200 Advanced Copier    3499.990
4190              Canon imageCLASS 2200 Advanced Copier    3499.990
2623              Canon imageCLASS 2200 Advanced Copier    2799.992
4218          Cubify CubeX 3D Printer Double Head Print    2399.992
6425              Canon imageCLASS 2200 Advanced Copier    2099.994
683           Cubify CubeX 3D Printer Triple Head Print    1999.995
318   Canon imageCLASS MF7460 Monochrome Digital Las...    1995.990
4098               Ibico EPK-21 Electric Binding System    1889.990
8488  HP Designjet T520 Inkjet Large Format Printer ...    1749.990

### 9. Count the number of orders per Region and per Segment.

In [15]:
print("\n--- Orders per Region ---")
print(df["Region"].value_counts())
print("\n--- Orders per Segment ---")
print(df["Segment"].value_counts())

--- Orders per Region ---
Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

--- Orders per Segment ---
Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

## PART 2: SORTING, FILTERING & VALUE COUNTS (PANDAS)

### 10. Sort the dataset by Sales in descending order and display top 10 rows.

In [16]:
print(df.sort_values(by="Sales", ascending=False).head(10))

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
2697    2698  CA-2014-145317   3/18/2014   3/23/2014  Standard Class
6826    6827  CA-2016-118689   10/2/2016   10/9/2016  Standard Class
8153    8154  CA-2017-140151   3/23/2017   3/25/2017     First Class
2623    2624  CA-2017-127180  10/22/2017  10/24/2017     First Class
4190    4191  CA-2017-166709  11/17/2017  11/22/2017  Standard Class
9039    9040  CA-2016-117121  12/17/2016  12/21/2016  Standard Class
4098    4099  CA-2014-116904   9/23/2014   9/28/2014  Standard Class
4277    4278  US-2016-107440   4/16/2016   4/20/2016  Standard Class
8488    8489  CA-2016-158841    2/2/2016    2/4/2016    Second Class
6425    6426  CA-2016-143714   5/23/2016   5/27/2016  Standard Class

     Customer ID       Customer Name      Segment        Country  \
2697    SM-20320         Sean Miller  Home Office  United States
6826    TC-20980        Tamara Chand    Corporate  United States
8153    RB-19360        Raymond Buch     Consumer  United States
2623    TA-21385        Tom Ashbrook  Home Office  United States
4190    HL-15040        Hunter Lopez     Consumer  United States
9039    AB-10105       Adrian Barton     Consumer  United States
4098    SC-20095        Sanjit Chand     Consumer  United States
4277    BS-11365        Bill Shonely    Corporate  United States
8488    SE-20110        Sanjit Engle     Consumer  United States
6425    CC-12370  Christopher Conant     Consumer  United States

               City  ...   Region       Product ID         Category  \
2697   Jacksonville  ...    South  TEC-MA-10002412       Technology
6826      Lafayette  ...  Central  TEC-CO-10004722       Technology
8153        Seattle  ...     West  TEC-CO-10004722       Technology
2623  New York City  ...     East  TEC-CO-10004722       Technology
4190         Newark  ...     East  TEC-CO-10004722       Technology
9039        Detroit  ...  Central  OFF-BI-10000545  Office Supplies
4098    Minneapolis  ...  Central  OFF-BI-10001120  Office Supplies
4277       Lakewood  ...     East  TEC-MA-10001047       Technology
8488      Arlington  ...    South  TEC-MA-10001127       Technology
6425   Philadelphia  ...     East  TEC-CO-10004722       Technology

     Sub-Category                                       Product Name  \
2697     Machines  Cisco TelePresence System EX90 Videoconferenci...
6826      Copiers              Canon imageCLASS 2200 Advanced Copier
8153      Copiers              Canon imageCLASS 2200 Advanced Copier
2623      Copiers              Canon imageCLASS 2200 Advanced Copier
4190      Copiers              Canon imageCLASS 2200 Advanced Copier
9039      Binders   GBC Ibimaster 500 Manual ProClick Binding System
4098      Binders               Ibico EPK-21 Electric Binding System
4277     Machines   3D Systems Cube Printer, 2nd Generation, Magenta
8488     Machines  HP Designjet T520 Inkjet Large Format Printer ...
6425      Copiers              Canon imageCLASS 2200 Advanced Copier

          Sales Quantity  Discount     Profit  Unit Price
2697  22638.480        6       0.5 -1811.0784    3773.080
6826  17499.950        5       0.0  8399.9760    3499.990
8153  13999.960        4       0.0  6719.9808    3499.990
2623  11199.968        4       0.2  3919.9888    2799.992
4190  10499.970        3       0.0  5039.9856    3499.990
9039   9892.740       13       0.0  4946.3700     760.980
4098   9449.950        5       0.0  4630.4755    1889.990
4277   9099.930        7       0.0  2365.9818    1299.990
8488   8749.950        5       0.0  2799.9840    1749.990
6425   8399.976        4       0.4  1119.9968    2099.994

[10 rows x 22 columns]

### 11. Sort by Profit in ascending order and display bottom 10 rows.

In [17]:
print(df.sort_values(by="Profit", ascending=True).head(10))

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
7772    7773  CA-2016-108196  11/25/2016   12/2/2016  Standard Class
683      684  US-2017-168116   11/4/2017   11/4/2017        Same Day
9774    9775  CA-2014-169019   7/26/2014   7/30/2014  Standard Class
3011    3012  CA-2017-134845   4/17/2017   4/23/2017  Standard Class
4991    4992  US-2017-122714   12/7/2017  12/13/2017  Standard Class
3151    3152  CA-2015-147830  12/15/2015  12/18/2015     First Class
5310    5311  CA-2017-131254  11/19/2017  11/21/2017     First Class
9639    9640  CA-2015-116638   1/28/2015   1/31/2015    Second Class
1199    1200  CA-2016-130946    4/8/2016   4/12/2016  Standard Class
2697    2698  CA-2014-145317   3/18/2014   3/23/2014  Standard Class

     Customer ID     Customer Name      Segment        Country          City  \
7772    CS-12505     Cindy Stewart     Consumer  United States     Lancaster
683     GT-14635    Grant Thornton    Corporate  United States    Burlington
9774    LF-17185       Luke Foster     Consumer  United States   San Antonio
3011    SR-20425    Sharelle Roach  Home Office  United States    Louisville
4991    HG-14965     Henry Goldwyn    Corporate  United States       Chicago
3151    NF-18385  Natalie Fritzler     Consumer  United States        Newark
5310    NC-18415       Nathan Cano     Consumer  United States       Houston
9639    JH-15985       Joseph Holt     Consumer  United States       Concord
1199    ZC-21910  Zuschuss Carroll     Consumer  United States       Houston
2697    SM-20320       Sean Miller  Home Office  United States  Jacksonville

      ...   Region       Product ID         Category Sub-Category  \
7772  ...     East  TEC-MA-10000418       Technology     Machines
683   ...    South  TEC-MA-10004125       Technology     Machines
9774  ...  Central  OFF-BI-10004995  Office Supplies      Binders
3011  ...     West  TEC-MA-10000822       Technology     Machines
4991  ...  Central  OFF-BI-10001120  Office Supplies      Binders
3151  ...     East  TEC-MA-10000418       Technology     Machines
5310  ...  Central  OFF-BI-10003527  Office Supplies      Binders
9639  ...    South  FUR-TA-10000198        Furniture       Tables
1199  ...  Central  OFF-BI-10004995  Office Supplies      Binders
2697  ...    South  TEC-MA-10002412       Technology     Machines

                                           Product Name      Sales Quantity  \
7772          Cubify CubeX 3D Printer Double Head Print   4499.985        5
683           Cubify CubeX 3D Printer Triple Head Print   7999.980        4
9774          GBC DocuBind P400 Electric Binding System   2177.584        8
3011          Lexmark MX611dhe Monochrome Laser Printer   2549.985        5
4991               Ibico EPK-21 Electric Binding System   1889.990        5
3151          Cubify CubeX 3D Printer Double Head Print   1799.994        2
5310  Fellowes PB500 Electric Punch Plastic Comb Bin...   1525.188        6
9639  Chromcraft Bull-Nose Wood Oval Conference Tabl...   4297.644       13
1199          GBC DocuBind P400 Electric Binding System   1088.792        4
2697  Cisco TelePresence System EX90 Videoconferenci...  22638.480        6

      Discount     Profit  Unit Price
7772       0.7 -6599.9780     899.997
683        0.5 -3839.9904    1999.995
9774       0.8 -3701.8928     272.198
3011       0.7 -3399.9800     509.997
4991       0.8 -2929.4845     377.998
3151       0.7 -2639.9912     899.997
5310       0.8 -2287.7820     254.198
9639       0.4 -1862.3124     330.588
1199       0.8 -1850.9464     272.198
2697       0.5 -1811.0784    3773.080

[10 rows x 22 columns]

### 12. Filter the dataset for orders in the Technology Category.

In [18]:
technology_orders = df[df["Category"] == "Technology"]

### 13. Filter orders where Profit > 500.

In [19]:
high_profit_orders = df[df["Profit"] > 500]

### 14. Use value_counts() to find the most frequent Ship Mode.

In [20]:
print(df["Ship Mode"].value_counts())

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

### 15. Use value_counts() to find the most frequent Category and Sub-Category.

In [21]:
print("\n--- Category Value Counts ---")
print(df["Category"].value_counts())
print("\n--- Sub-Category Value Counts ---")
print(df["Sub-Category"].value_counts())

--- Category Value Counts ---
Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

--- Sub-Category Value Counts ---
Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [23]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Unit Price
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,130.9800
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,243.9800
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,7.3100
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,191.5155
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,11.1840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,8.4160
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,45.9800
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,129.2880
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,7.4000
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,121.5800

## PART 3: CREATING NEW COLUMNS & CALCULATIONS (PANDAS + NUMPY)

### 16. Create a new column Revenue as Sales - Discount.

In [24]:
df["Revenue"] = df["Sales"] - df["Discount"]

### 17. Create a new column Profit Ratio as Profit / Sales.

In [25]:
df["Profit Ratio"] = df["Profit"] / df["Sales"]

### 18. Create a new column High Sales Flag using NumPy (True if Sales > 1000 else False).

In [26]:
df["High Sales Flag"] = np.where(df["Sales"] > 1000, True, False)

### 19. Calculate total sales per Region using a Pandas column operation.

In [27]:
sales_per_region = df.groupby("Region")["Sales"].transform("sum")

### 20. Calculate average profit per Category using a column operation.

In [28]:
avg_profit_per_category = df.groupby("Category")["Profit"].transform("mean")

### 21. Using NumPy, create a new column Sales Log as the natural log of Sales.

In [29]:
df["Sales Log"] = np.log(df["Sales"])

### 22. Using NumPy, create a new column Profit Squared as Profit squared.

In [30]:
df["Profit Squared"] = np.square(df["Profit"])

In [31]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Unit Price,Revenue,Profit Ratio,High Sales Flag,Sales Log,Profit Squared
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,130.9800,261.9600,0.1600,False,5.568192,1756.749865
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,243.9800,731.9400,0.3000,False,6.595699,48216.254724
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,7.3100,14.6200,0.4700,False,2.682390,47.216138
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,191.5155,957.1275,-0.4000,False,6.864407,146712.746961
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,11.1840,22.1680,0.1125,False,3.107631,6.332269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,25.2480,3,0.20,4.1028,8.4160,25.0480,0.1625,False,3.228747,16.832968
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,91.9600,2,0.00,15.6332,45.9800,91.9600,0.1700,False,4.521354,244.396942
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,258.5760,2,0.20,19.3932,129.2880,258.3760,0.0750,False,5.555190,376.096206
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,29.6000,4,0.00,13.3200,7.4000,29.6000,0.4500,False,3.387774,177.422400
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,243.1600,2,0.00,72.9480,121.5800,243.1600,0.3000,False,5.493720,5321.410704

## PART 4: AGGREGATION AND GROUPBY (PANDAS)

### 23. Find total sales per Region.

In [32]:
total_sales_region = df.groupby("Region")["Sales"].sum()
print("\n--- Total Sales per Region ---")
print(total_sales_region)

--- Total Sales per Region ---
Region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

### 24. Find average profit per Category.

In [33]:
avg_profit_category = df.groupby("Category")["Profit"].mean()
print("\n--- Average Profit per Category ---")
print(avg_profit_category)

--- Average Profit per Category ---
Category
Furniture           8.699327
Office Supplies    20.327050
Technology         78.752002
Name: Profit, dtype: float64

### 25. Find maximum and minimum sales per Sub-Category.

In [34]:
sales_min_max = df.groupby("Sub-Category")["Sales"].agg(["min", "max"])
print("\n--- Min & Max Sales per Sub-Category ---")
print(sales_min_max)

--- Min & Max Sales per Sub-Category ---
                  min        max
Sub-Category
Accessories     0.990   3347.370
Appliances      0.444   2625.120
Art             1.344   1113.024
Binders         0.556   9892.740
Bookcases      35.490   4404.900
Chairs         26.640   4416.174
Copiers       299.990  17499.950
Envelopes       1.632    604.656
Fasteners       1.240     93.360
Furnishings     1.892   1336.440
Labels          2.088    786.480
Machines       11.560  22638.480
Paper           3.380    733.950
Phones          2.970   4548.810
Storage         4.464   2934.330
Supplies        1.744   8187.650
Tables         24.368   4297.644

### 26. Count the number of orders per Customer Segment.

In [35]:
orders_per_segment = df.groupby("Segment")["Order ID"].nunique()
print("\n--- Order Count per Segment ---")
print(orders_per_segment)

--- Order Count per Segment ---
Segment
Consumer       2586
Corporate      1514
Home Office     909
Name: Order ID, dtype: int64

### 27. Find total quantity sold per Product Name and list top 10 products.

In [36]:
top_10_quantity_products = (
    df.groupby("Product Name")["Quantity"].sum().nlargest(10)
)
print("\n--- Top 10 Products by Total Quantity Sold ---")
print(top_10_quantity_products)

--- Top 10 Products by Total Quantity Sold ---
Product Name
Staples                                                       215
Staple envelope                                               170
Easy-staple paper                                             150
Staples in misc. colors                                        86
KI Adjustable-Height Table                                     74
Avery Non-Stick Binders                                        71
Storex Dura Pro Binders                                        71
GBC Premium Transparent Covers with Diagonal Lined Pattern     67
Situations Contoured Folding Chairs, 4/Set                     64
Staple-based wall hangings                                     62
Name: Quantity, dtype: int64

### 28. Find total sales and total profit for each Category per Region.

In [37]:
cat_region_summary = df.groupby(["Region", "Category"])[["Sales", "Profit"]].sum()
print("\n--- Total Sales & Profit per Category & Region ---")
print(cat_region_summary)

--- Total Sales & Profit per Category & Region ---
                               Sales      Profit
Region  Category
Central Furniture        163797.1638  -2871.0494
        Office Supplies  167026.4150   8879.9799
        Technology       170416.3120  33697.4320
East    Furniture        208291.2040   3046.1658
        Office Supplies  205516.0550  41014.5791
        Technology       264973.9810  47462.0351
South   Furniture        117298.6840   6771.2061
        Office Supplies  125651.3130  19986.3928
        Technology       148771.9080  19991.8314
West    Furniture        252612.7435  11504.9503
        Office Supplies  220853.2490  52609.8490
        Technology       251991.8320  44303.6496

### 29. Find average discount per Sub-Category per Region.

In [38]:
avg_discount_subcat_region = df.groupby(["Region", "Sub-Category"])["Discount"].mean()
print("\n--- Avg Discount per Sub-Category per Region ---")
print(avg_discount_subcat_region)

--- Avg Discount per Sub-Category per Region ---
Region   Sub-Category
Central  Accessories     0.124590
         Appliances      0.448780
         Art             0.122727
         Binders         0.509290
         Bookcases       0.232800
                           ...
West     Paper           0.031556
         Phones          0.200000
         Storage         0.030827
         Supplies        0.037681
         Tables          0.200000
Name: Discount, Length: 68, dtype: float64

### 30. Count the number of orders per Category per Segment.

In [39]:
orders_cat_segment = df.groupby(["Segment", "Category"])["Order ID"].nunique()
print("\n--- Orders per Category per Segment ---")
print(orders_cat_segment)

--- Orders per Category per Segment ---
Segment      Category
Consumer     Furniture           917
             Office Supplies    1922
             Technology          809
Corporate    Furniture           540
             Office Supplies    1142
             Technology          454
Home Office  Furniture           307
             Office Supplies     678
             Technology          281
Name: Order ID, dtype: int64

## PART 5: NUMPY ARRAY TASKS

### 31. Convert Sales column to a NumPy array and find statistics.

In [40]:
sales_arr = df["Sales"].to_numpy()
print("\n--- NumPy Sales Array Statistics ---")
print(f"Maximum: {np.max(sales_arr):.2f}")
print(f"Minimum: {np.min(sales_arr):.2f}")
print(f"Mean: {np.mean(sales_arr):.2f}")
print(f"Median: {np.median(sales_arr):.2f}")
print(f"Standard Deviation: {np.std(sales_arr):.2f}")

--- NumPy Sales Array Statistics ---
Maximum: 22638.48
Minimum: 0.44
Mean: 229.86
Median: 54.49
Standard Deviation: 623.21

### 32. Using NumPy, find all orders where Profit > 500.

In [41]:
profit_arr = df["Profit"].to_numpy()
high_profit_indices = np.where(profit_arr > 500)[0]
high_profit_orders_np = df.iloc[high_profit_indices]

### 33. Using NumPy, create a normalized Sales column using (Sales - mean) / std.

In [42]:
sales_mean = np.mean(sales_arr)
sales_std = np.std(sales_arr)
df["Sales Normalized"] = (sales_arr - sales_mean) / sales_std

### 34. Using NumPy, calculate the sum of Revenue for orders where Profit Ratio > 0.2.

In [43]:
revenue_arr = df["Revenue"].to_numpy()
profit_ratio_arr = df["Profit Ratio"].to_numpy()
high_ratio_revenue_sum = np.sum(revenue_arr[profit_ratio_arr > 0.2])
print(f"\nSum of Revenue (Profit Ratio > 0.2): {high_ratio_revenue_sum:.2f}")

Sum of Revenue (Profit Ratio > 0.2): 1069707.03

### 35. Using NumPy, find the indices of the top 5 highest Sales orders.

In [44]:
top_5_sales_indices = np.argsort(sales_arr)[-5:][::-1]
print("\n--- Top 5 Sales Indices ---")
print(top_5_sales_indices)
print("\n--- Top 5 Highest Sales Orders ---")
print(df.iloc[top_5_sales_indices][["Order ID", "Sales"]])

--- Top 5 Sales Indices ---
[2697 6826 8153 2623 4190]

--- Top 5 Highest Sales Orders ---
            Order ID      Sales
2697  CA-2014-145317  22638.480
6826  CA-2016-118689  17499.950
8153  CA-2017-140151  13999.960
2623  CA-2017-127180  11199.968
4190  CA-2017-166709  10499.970

In [45]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Quantity,Discount,Profit,Unit Price,Revenue,Profit Ratio,High Sales Flag,Sales Log,Profit Squared,Sales Normalized
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,2,0.00,41.9136,130.9800,261.9600,0.1600,False,5.568192,1756.749865,0.051510
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,0.00,219.5820,243.9800,731.9400,0.3000,False,6.595699,48216.254724,0.805633
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,2,0.00,6.8714,7.3100,14.6200,0.4700,False,2.682390,47.216138,-0.345368
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,5,0.45,-383.0310,191.5155,957.1275,-0.4000,False,6.864407,146712.746961,1.167688
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,2,0.20,2.5164,11.1840,22.1680,0.1125,False,3.107631,6.332269,-0.332935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,3,0.20,4.1028,8.4160,25.0480,0.1625,False,3.228747,16.832968,-0.328314
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,2,0.00,15.6332,45.9800,91.9600,0.1700,False,4.521354,244.396942,-0.221269
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,2,0.20,19.3932,129.2880,258.3760,0.0750,False,5.555190,376.096206,0.046080
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,4,0.00,13.3200,7.4000,29.6000,0.4500,False,3.387774,177.422400,-0.321331
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,2,0.00,72.9480,121.5800,243.1600,0.3000,False,5.493720,5321.410704,0.021344