In [1]:
import pandas as pd

## DATA LOADING & OVERVIEW

### 1. Load the dataset

In [4]:
df = pd.read_csv("google.csv")

### 2. Display the first 5 rows

In [7]:
print(df.head())

                                                 App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1
1                                Coloring book moana  ART_AND_DESIGN     3.9
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone
1     967   14M     500,000+  Free     0       Everyone
2   87510  8.7M   5,000,000+  Free     0       Everyone
3  215644   25M  50,000,000+  Free     0           Teen
4     967  2.8M     100,000+  Free     0       Everyone

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0
1  Art & Design;Pretend Play  January 15, 2018               2.0.0
2               Art & Design    August 1, 2018               1.2.4
3               Art & Design      June 8, 2018  Varies with device
4    Art & Design;Creativity     June 20, 2018                 1.1

    Android Ver
0  4.0.3 and up
1  4.0.3 and up
2  4.0.3 and up
3    4.2 and up
4    4.4 and up

### 3. Display the last 5 rows

In [8]:
print(df.tail())

                                                 App             Category  \
10836                               Sya9a Maroc - FR               FAMILY
10837               Fr. Mike Schmitz Audio Teachings               FAMILY
10838                         Parkinson Exercices FR              MEDICAL
10839                  The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10840  iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

       Rating Reviews                Size     Installs  Type Price  \
10836     4.5      38                 53M       5,000+  Free     0
10837     5.0       4                3.6M         100+  Free     0
10838     NaN       3                9.5M       1,000+  Free     0
10839     4.5     114  Varies with device       1,000+  Free     0
10840     4.5  398307                 19M  10,000,000+  Free     0

      Content Rating             Genres      Last Updated         Current Ver  \
10836       Everyone          Education     July 25, 2017                1.48
10837       Everyone          Education      July 6, 2018                 1.0
10838       Everyone            Medical  January 20, 2017                 1.0
10839     Mature 17+  Books & Reference  January 19, 2015  Varies with device
10840       Everyone          Lifestyle     July 25, 2018  Varies with device

              Android Ver
10836          4.1 and up
10837          4.1 and up
10838          2.2 and up
10839  Varies with device
10840  Varies with device

### 4. Check dataset structure and non-null counts

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 2.2 MB

### 5. Generate summary statistics for all columns

In [11]:
print(df.describe(include="all"))

           App Category       Rating Reviews                Size    Installs  \
count    10841    10841  9367.000000   10841               10841       10841
unique    9660       34          NaN    6002                 462          22
top     ROBLOX   FAMILY          NaN       0  Varies with device  1,000,000+
freq         9     1972          NaN     596                1695        1579
mean       NaN      NaN     4.193338     NaN                 NaN         NaN
std        NaN      NaN     0.537431     NaN                 NaN         NaN
min        NaN      NaN     1.000000     NaN                 NaN         NaN
25%        NaN      NaN     4.000000     NaN                 NaN         NaN
50%        NaN      NaN     4.300000     NaN                 NaN         NaN
75%        NaN      NaN     4.500000     NaN                 NaN         NaN
max        NaN      NaN    19.000000     NaN                 NaN         NaN

         Type  Price Content Rating Genres    Last Updated  \
count   10840  10841          10840  10841           10841
unique      3     93              6    120            1378
top      Free      0       Everyone  Tools  August 3, 2018
freq    10039  10040           8714    842             326
mean      NaN    NaN            NaN    NaN             NaN
std       NaN    NaN            NaN    NaN             NaN
min       NaN    NaN            NaN    NaN             NaN
25%       NaN    NaN            NaN    NaN             NaN
50%       NaN    NaN            NaN    NaN             NaN
75%       NaN    NaN            NaN    NaN             NaN
max       NaN    NaN            NaN    NaN             NaN

               Current Ver Android Ver
count                10833       10838
unique                2832          33
top     Varies with device  4.1 and up
freq                  1459        2451
mean                   NaN         NaN
std                    NaN         NaN
min                    NaN         NaN
25%                    NaN         NaN
50%                    NaN         NaN
75%                    NaN         NaN
max                    NaN         NaN

### 6. Display all column names and their data types

In [12]:
print(df.dtypes)

App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

## DATA CLEANING (REAL-WORLD SCENARIOS)

### 7. Identify missing values in each column

In [13]:
print(df.isnull().sum())

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

### 8. Remove rows where "Rating" is missing

In [14]:
df = df.dropna(subset=["Rating"])

### 9. Fill missing values in "Type" with the most frequent value (mode)

In [15]:
df["Type"] = df["Type"].fillna(df["Type"].mode()[0])

### 10. Remove duplicate records from the dataset

In [24]:
df = df.drop_duplicates()

### 11. Clean "Installs" (remove '+', ',' and non-numeric entries if present, convert to int)

In [33]:
df["Installs"] = (
    df["Installs"]
    .astype(str)
    .str.replace("+", "", regex=False)
    .str.replace(",", "", regex=False)
)

### 12. Clean "Price" (remove '$' and convert to float)

In [35]:
df["Installs"] = (
    df["Installs"]
    .astype(str)
    .str.replace("+", "", regex=False)
    .str.replace(",", "", regex=False)
)

### 13. Convert "Reviews" column to integer type

In [26]:
df["Reviews"] = df["Reviews"].astype(int)

### 14. Convert "Last Updated" column to datetime format

In [30]:
df["Last Updated"] = pd.to_datetime(df["Last Updated"])

##  STRING OPERATIONS

### 15. Convert all app names to lowercase

In [36]:
df["App"] = df["App"].str.lower()

### 16. Convert category names to uppercase

In [37]:
df["Category"] = df["Category"].str.upper()

### 17. Split the "Genres" column into multiple parts (takes the first genre)

In [38]:
df["Primary_Genre"] = df["Genres"].str.split(";").str[0]

### 18. Replace unwanted text patterns in "Category" (e.g., replacing underscores with spaces)

In [39]:
df["Category"] = df["Category"].str.replace("_", " ")

In [41]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Primary_Genre
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,Art & Design
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,Art & Design
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,Art & Design
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,Art & Design
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,Art & Design
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,fr calculator,FAMILY,4.0,7,2.6M,500,Free,0.0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,Education
10836,sya9a maroc - fr,FAMILY,4.5,38,53M,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up,Education
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up,Education
10839,the scp foundation db fr nn5n,BOOKS AND REFERENCE,4.5,114,Varies with device,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,Books & Reference
10840,ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,Lifestyle

## FILTERING & SELECTION

### 19. Filter apps with rating greater than 4.5

In [42]:
high_rated = df[df["Rating"] > 4.5]

### 20. Find all free apps

In [43]:
free_apps = df[df["Price"] == 0]

### 21. Filter apps with installs greater than 1,000,000

In [48]:
df["Installs"] = pd.to_numeric(df["Installs"])

### 22. Select apps belonging to multiple categories

In [45]:
target_categories = ["GAME", "FAMILY", "TOOLS"]
selected_categories = df[df["Category"].isin(target_categories)]

### 23. Perform filtering using query syntax

In [46]:
query_filtered = df.query("Rating > 4.0 and Price == 0")

## 5. FEATURE ENGINEERING

### 24. Create a new column "Revenue" using installs and price

In [49]:
df["Revenue"] = df["Installs"] * df["Price"]

### 25. Categorize apps into rating groups (Low, Medium, High)

In [50]:
df["Rating_Group"] = pd.cut(
    df["Rating"], bins=[0, 3.0, 4.2, 5.0], labels=["Low", "Medium", "High"]
)

### 26. Create a new column to flag high-install apps (>1M installs)

In [51]:
df["Is_High_Install"] = df["Installs"].apply(lambda x: 1 if x > 1000000 else 0)

### 27. Convert "Type" column into numeric values (Free=0, Paid=1)

In [52]:
df["Type_Numeric"] = df["Type"].map({"Free": 0, "Paid": 1})

In [53]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Primary_Genre,Revenue,Rating_Group,Is_High_Install,Type_Numeric
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,Art & Design,0.0,Medium,0,0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,Art & Design,0.0,Medium,0,0
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,Art & Design,0.0,High,1,0
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,Art & Design,0.0,High,1,0
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,Art & Design,0.0,High,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,fr calculator,FAMILY,4.0,7,2.6M,500,Free,0.0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,Education,0.0,Medium,0,0
10836,sya9a maroc - fr,FAMILY,4.5,38,53M,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up,Education,0.0,High,0,0
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up,Education,0.0,High,0,0
10839,the scp foundation db fr nn5n,BOOKS AND REFERENCE,4.5,114,Varies with device,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,Books & Reference,0.0,High,0,0
10840,ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,Lifestyle,0.0,High,1,0

## SORTING & RANKING

### 28. Sort apps by number of installs in descending order

In [54]:
sorted_by_installs = df.sort_values(by="Installs", ascending=False)

### 29. Identify top 10 apps based on number of reviews

In [55]:
top_10_reviewed = df.nlargest(10, "Reviews")

### 30. Identify bottom 10 apps based on installs

In [56]:
bottom_10_installed = df.nsmallest(10, "Installs")

### 31. Rank apps based on rating

In [57]:
df["Rating_Rank"] = df["Rating"].rank(ascending=False, method="min")

## GROUPBY & AGGREGATION

### 32. Calculate average rating for each category

In [58]:
avg_rating_per_cat = df.groupby("Category")["Rating"].mean()

### 33. Calculate total installs for each category

In [59]:
total_installs_per_cat = df.groupby("Category")["Installs"].sum()

### 34. Count the number of apps in each category

In [60]:
app_count_per_cat = df["Category"].value_counts()

### 35. Perform multiple aggregations (mean rating, max installs) per category

In [61]:
cat_summary = df.groupby("Category").agg({"Rating": "mean", "Installs": "max"})

In [62]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Primary_Genre,Revenue,Rating_Group,Is_High_Install,Type_Numeric,Rating_Rank
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,Art & Design,0.0,Medium,0,0,5752.0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,Art & Design,0.0,Medium,0,0,6948.0
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,Art & Design,0.0,High,1,0,587.0
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,Art & Design,0.0,High,1,0,1839.0
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,Art & Design,0.0,High,0,0,3848.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,fr calculator,FAMILY,4.0,7,2.6M,500,Free,0.0,Everyone,Education,2017-06-18,1.0.0,4.1 and up,Education,0.0,Medium,0,0,6409.0
10836,sya9a maroc - fr,FAMILY,4.5,38,53M,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up,Education,0.0,High,0,0,1839.0
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up,Education,0.0,High,0,0,1.0
10839,the scp foundation db fr nn5n,BOOKS AND REFERENCE,4.5,114,Varies with device,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,Books & Reference,0.0,High,0,0,1839.0
10840,ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,Lifestyle,0.0,High,1,0,1839.0

##  MERGE / JOIN / CONCAT

### 36. Split the dataset into multiple tables

In [63]:
apps_info = df[["App", "Category", "Rating"]].drop_duplicates(subset=["App"])
installs_info = df[["App", "Installs", "Reviews"]].drop_duplicates(subset=["App"])
pricing_info = df[["App", "Type", "Price", "Revenue"]].drop_duplicates(subset=["App"])

### 37. Merge app details with installs data using a common column

In [64]:
merged_df = pd.merge(apps_info, installs_info, on="App")

### 38. Perform an inner join

In [65]:
inner_merged = pd.merge(apps_info, installs_info, on="App", how="inner")

### 39. Perform a left join and identify missing values created after the merge

In [66]:
left_merged = pd.merge(apps_info, pricing_info, on="App", how="left")
missing_after_left_join = left_merged.isnull().sum()

### 40. Combine two DataFrames vertically to simulate adding new data

In [ ]:
df_part1 = df.iloc[:5000]
df_part2 = df.iloc[5000:]
concatenated_df = pd.concat([df_part1, df_part2], axis=0)